# Generated by Django 4.1.3 on 2023-02-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_follow_follower_alter_follow_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='leader',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='user',
        ),
    ]
