# Generated by Django 4.1.3 on 2023-02-23 19:27

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_datetime_alter_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=network.models.now, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
