# Generated by Django 4.1.3 on 2023-02-24 01:48

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        AddDefaultValue(
             model_name='post',
             name='like_count',
             value=0
         )
    ]
