# Generated by Django 4.1.3 on 2023-02-28 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
