# Generated by Django 4.1.3 on 2023-02-28 20:00

from django.db import migrations, models
import uuid

def gen_uuid(apps, shcema_editor):
    Like = apps.get_model('network', 'Like')
    for row in Like.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_like_uuid_alter_like_post_alter_like_user_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
