# Generated by Django 4.1.3 on 2023-02-28 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20230228_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
