# Generated by Django 4.1.3 on 2023-03-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_like_post_alter_like_user_like_unique_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='uuid',
        ),
    ]
