# Generated by Django 4.1.3 on 2023-03-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_alter_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=280, verbose_name=''),
        ),
    ]
